### ISSUE TITLE
Relative pathname to scheme file gets prefixed with directory of yaml to validate

### ISSUE THREAD

**Issue by chickenandpork** [k-ogawa-1988/pre-commit-yamale#1]
I ran into a problem: in using a `.pre-commit` to trigger a validation (essentially: validate any `values.yaml` file), the schema file was part of the repo.  The problem there is that the schema file cannot be an absolute path due to being on a different pathname on each developer's environment.

Cannot use an absolute path for the `schema`, so had to be a local path, and it would get prefixed with the directory of the yaml file being checked.

How can I, for example:

```
  - repo: https://github.com/k-ogawa-1988/yamale-pre-commit
    rev: v0.0.2
    hooks:
      - id: yamale-validate
        files: values.yaml
        args:
          - '--no-strict'
          - '-s'
          - tools/pre-commit/yamale-schema.yaml
```
.. where I want to:
 - check every `values.yaml`
 - keep the schema in a local ./tools/ directory in the repo
 - allow the repos to be in my /home/chickenandpork/awesome-project/ directory, but in my colleague's /home/n00b/awesome-project/ directory
 
That schema is a simple check such as:
```
tools/pre-commit/yamale-schema.yaml 
resources:
  limits:
    memory: include('RAMSize', required=True)
    cpu: include('CPUSize', required=True)
  requests:
    memory: include('RAMSize', required=True)
    cpu: include('CPUSize', required=True)

---
CPUSize: str(matches='[0-9]+(m)?')
RAMSize: str(matches='[0-9]+(Ki|Mi|Gi)')
```
